---
 - name: Email Notification
  ansible.builtin.include_tasks:
    file: task_mailnotification.yml
 - name: Linux Known Host Policy
  ansible.builtin.include_tasks:
    file: task_linuxknownhosts.yml
...
