---
- name: Linux Trusted Host Policy - KnownHosts
  ansible.windows.win_shell: |
    $current = (Get-VBRLinuxTrustedHostPolicy).type
    if ($current -ne 'KnownHosts') {
        Set-VBRLinuxTrustedHostPolicy -Type KnownHosts
        Write-Output "LINUX_KNOWN_HOSTS_ENABLED"
    } else {
        Write-Output "LINUX_KNOWN_HOSTS_ALREADY_ENABLED"
    }
  register: veeam_security_linux_trusted_host_config
  changed_when: "'LINUX_KNOWN_HOSTS_ENABLED' in veeam_security_linux_trusted_host_config.stdout"
...
